-- Aqui podemos criar instruções SQL DML (Insert, Update, Delete)
-- Podem haver mais uma instrução, separadas por ponto e vírgula (;)

INSERT INTO regras (minimo_pets, maximo_pets)
VALUES
(1, 10);

INSERT INTO raca (codigo, nome)
VALUES
('VIRA_LATA', 'Vira Lata'),
('SIAMES', 'Siamês'),
('LABRADOR_RETRIEVER', 'Labrador Retriever'),
('PASTOR_ALEMAO', 'Pastor Alemão'),
('GOLDEN_RETRIEVER', 'Golden Retriever'),
('FRENCH_BULLDOG', 'Bulldog Francês'),
('BULLDOG', 'Bulldogue'),
('POODLE', 'Poodle'),
('BEAGLE', 'Beagle'),
('ROTTWEILER', 'Rottweiler'),
('POINTER', 'Pointer'),
('YORKSHIRE_TERRIER', 'Yorkshire Terrier'),
('BOXER', 'Boxer'),
('DACHSHUND', 'Dachshund'),
('SIBERIAN_HUSKY', 'Husky Siberiano'),
('GREAT_DANE', 'Dogue Alemão'),
('DOBERMANN', 'Dobermann'),
('SHIH_TZU', 'Shih Tzu'),
('AUSTRALIAN_SHEPHERD', 'Australian Shepherd'),
('POMERANIAN', 'Pomerânia'),
('BULL_TERRIER', 'Bull Terrier'),
('CHIHUAHUA', 'Chihuahua'),
('MALTESE', 'Maltês'),
('BASSET_HOUND', 'Basset Hound'),
('CAO_DE_AGUA_PORTUGUES', 'Cão de Água Português'),
('SAMOYED', 'Samoieda'),
('BICHON_FRISE', 'Bichon Frisé'),
('NEWFOUNDLAND', 'Terra Nova'),
('PAPILLON', 'Papillon'),
('STAFFORDSHIRE_BULL_TERRIER', 'Staffordshire Bull Terrier'),
('AKITA', 'Akita'),
('DALMATIAN', 'Dálmata'),
('WHIPPET', 'Whippet'),
('IRISH_SETTER', 'Irish Setter'),
('COCKER_SPANIEL', 'Cocker Spaniel'),
('ENGLISH_SPRINGER_SPANIEL', 'Springer Spaniel Inglês'),
('TIBETAN_MASTIFF', 'Mastim Tibetano'),
('SHAR_PEI', 'Shar Pei'),
('BULLMASTIFF', 'Bullmastiff'),
('BERNESE_MOUNTAIN_DOG', 'Boiadeiro Bernês'),
('CHOW_CHOW', 'Chow Chow'),
('KELPIE_AUSTRALIANO', 'Kelpie Australiano'),
('BRAZILIAN_FILA', 'Fila Brasileiro'),
('OTTERHOUND', 'Otterhound'),
('SALUKI', 'Saluki'),
('BORZOI', 'Barzoi'),
('PEKINGESE', 'Pequinês'),
('GREAT_PYRENEES', 'Grande Pirineus'),
('ANATOLIAN_SHEPHERD', 'Pastor Anatólio'),
('IRISH_WOLFHOUND', 'Wolfhound Irlandês'),
('TIBETAN_TERRIER', 'Terrier Tibetano'),
('PERSA', 'Persa'),
('SIAMESE', 'Siamês'),
('MAINE_COON', 'Maine Coon'),
('RAGDOLL', 'Ragdoll'),
('SPHYNX', 'Sphynx'),
('BENGAL', 'Bengal'),
('ABYSSINIAN', 'Abissínio'),
('ORIENTAL_SHORTHAIR', 'Oriental'),
('RUSSIAN_BLUE', 'Azul Russo'),
('SCOTTISH_FOLD', 'Scottish Fold'),
('BRITISH_SHORTHAIR', 'British Shorthair'),
('AMERICAN_SHORTHAIR', 'American Shorthair'),
('EXOTIC_SHORTHAIR', 'Exotic Shorthair'),
('TURKISH_ANGORA', 'Angorá Turco'),
('TURKISH_VAN', 'Van Turco'),
('NORWEGIAN_FOREST', 'Floresta da Noruega'),
('SINGAPURA', 'Singapura'),
('CORNISH_REX', 'Cornish Rex'),
('DEVON_REX', 'Devon Rex'),
('BURMESE', 'Burmese'),
('TONKINESE', 'Tonkinese'),
('JAPANESE_BOBTAIL', 'Japanese Bobtail'),
('BALINESE', 'Balinês'),
('HAVANA_BROWN', 'Havana Brown'),
('KHAO_MANEE', 'Khao Manee'),
('SELKIRK_REX', 'Selkirk Rex'),
('NEBELUNG', 'Nebelung'),
('SOMALI', 'Somali'),
('PIXIEBOB', 'Pixie-bob'),
('OCICAT', 'Ocicat'),
('CHARTREUX', 'Chartreux'),
('LAPERM', 'LaPerm'),
('EGYPTIAN_MAU', 'Egyptian Mau'),
('RAGAMUFFIN', 'Ragamuffin'),
('MANX', 'Manx'),
('TOYGER', 'Toyger'),
('EUROPEAN_SHORTHAIR', 'European Shorthair'),
('AUSTRALIAN_MIST', 'Australian Mist'),
('BURMILLA', 'Burmilla'),
('BRITISH_LONGHAIR', 'British Longhair'),
('AMERICAN_BOBTAIL', 'American Bobtail'),
('KORAT', 'Korat'),
('PETERBALD', 'Peterbald'),
('SNOWSHOE', 'Snowshoe'),
('CALIFORNIA_SPANGLED', 'California Spangled'),
('SERENGETI', 'Serengeti'),
('CHAUSIE', 'Chausie'),
('BOMBAY', 'Bombay'),
('HIMALAYAN', 'Himalayan'),
('THAI', 'Thai'),
('DUTCH_RABBIT', 'Dutch'),
('HOLLAND_LOP', 'Holland Lop'),
('NETHERLAND_DWARF', 'Netherland Dwarf'),
('FLEMISH_GIANT', 'Flemish Giant'),
('LIONHEAD', 'Lionhead'),
('MINI_REX', 'Mini Rex'),
('REX_RABBIT', 'Rex'),
('ENGLISH_ANGORA', 'English Angora'),
('FRENCH_LOP', 'French Lop'),
('AMERICAN_SABLE', 'American Sable'),
('CANARY', 'Canário'),
('BUDGERIGAR', 'Periquito'),
('COCKATIEL', 'Calopsita'),
('BLUE_MACAW', 'Arara Azul'),
('CANINDE_MACAW', 'Arara Canindé'),
('COCKATOO', 'Cacatua'),
('LOVEBIRD', 'Agapornis'),
('CONURE', 'Conure'),
('AMAZON_PARROT', 'Papagaio Amazônico'),
('AFRICAN_GREY', 'Papagaio do Congo (African Grey)'),
('PARRAKEET', 'Periquito (Parrakeet)'),
('TUCAN', 'Tucano'),
('DOVE', 'Pomba'),
('SILVER_CHEEKED_TUCAN', 'Tucano Prateado'),
('FINCH', 'Pintassilgo'),
('GOLDFINCH', 'Cardeal'),
('MYNA', 'Myna'),
('RINGNECK_PARROT', 'Papagaio de Colar'),
('LORY', 'Lóris'),
('LOVEBIRD_ROSEICOLLIS', 'Agapornis Roseicollis'),
('QUAKER_PARROT', 'Quaker'),
('MACAW_GREENWING', 'Arara de Asa Verde'),
('MACAW_RED_AND_GREEN', 'Arara Vermelha e Verde'),
('HYACINTH_MACAW', 'Arara Hyacinth'),
('LOUISE_TIT', 'Siskin'),
('SILVER_PHEASANT', 'Faisão Prateado'),
('PARROTLET', 'Parrotlet'),
('BUDGERIGAR_FANCY', 'Periquito Fancy'),
('CANARY_SINGER', 'Canário Cantor'),
('PARADISE_LOREK', 'Lóris do Paraíso'),
('PELICAN', 'Pelicano'),
('KINGFISHER', 'Martim-pescador'),
('BLACKBIRD', 'Melro'),
('STARLING', 'Estorninho'),
('GROSBEAK', 'Cardealito'),
('HORNBILL', 'Calaú'),
('RAPTOR_SMALL', 'Falcão Pequeno'),
('DANISH_SONGTHRUSH', 'Sabiá Dinamarquês'),
('VULTURE_SMALL', 'Urubu Pequeno'),
('HOOPOE', 'Upupa'),
('KAKAPO', 'Kakapo'),
('KEA', 'Kea'),
('LOON', 'Mergulhão'),
('WREN', 'Carrinho'),
('NIGHTINGALE', 'Rouxinol'),
('WOODPECKER', 'Pica-pau'),
('SILVERPARROT', 'Papagaio Prateado'),
('TIT', 'Chapim');


INSERT INTO especie (codigo, nome)
VALUES
('CAO', 'Cachorro'),
('GATO', 'Gato'),
('PASSARO', 'Pássaro'),
('ROEDOR', 'Roedor'),
('REPTIL', 'Réptil');


INSERT INTO pet (nome_pet, nome_dono, especie_codigo, raca_codigo, email_dono, peso, altura, nascimento, validade_chip, cpf_dono, telefone_dono, ativo) VALUES
('Fido', 'João Silva', 'CAO', 'VIRA_LATA', 'joao.silva@example.com', 15.5, 0.5, '2020-01-15', '2030-01-15', '12345678901', '(11) 98765-4321', true),
('Miau', 'Maria Souza', 'GATO', 'SIAMES', 'maria.souza@example.com', 4.2, 0.25, '2021-05-20', '2031-05-20', '10987654321', '(21) 91234-5678', true),
('Piu', 'Carlos Pereira', 'PASSARO', 'PERSA', 'carlos.pereira@example.com', 0.1, 0.1, '2022-02-10', '2032-02-10', '56789012345', '(31) 99999-8888', false),
('Rex', 'Ana Costa', 'CAO', 'PASTOR_ALEMAO', 'ana.costa@example.com', 30.0, 0.7, '2019-11-30', '2029-11-30', '98765432109', '(41) 98888-7777', true);
